//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Main.View.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRL.Main.View.Localization.HomeView", typeof(HomeView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wojciech Kowalik, Konrad Miśkiewicz, Mateusz Pielat.
        /// </summary>
        internal static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        internal static string authorsHeader {
            get {
                return ResourceManager.GetString("authorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty of Mathematics and Information Science.
        /// </summary>
        internal static string faculty {
            get {
                return ResourceManager.GetString("faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatyka.
        /// </summary>
        internal static string major {
            get {
                return ResourceManager.GetString("major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dr Paweł Rzążewski.
        /// </summary>
        internal static string promoter {
            get {
                return ResourceManager.GetString("promoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoter:.
        /// </summary>
        internal static string promoterHeader {
            get {
                return ResourceManager.GetString("promoterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation of a robot in a labirynth.
        /// </summary>
        internal static string thesis {
            get {
                return ResourceManager.GetString("thesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering thesis.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warsaw University of Technology.
        /// </summary>
        internal static string university {
            get {
                return ResourceManager.GetString("university", resourceCulture);
            }
        }
    }
}
