//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.CommonsTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRL.CommonsTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;480&quot; height=&quot;480&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;rect width=&quot;480&quot; height=&quot;480&quot; fill=&quot;rgb(1, 47, 135)&quot; /&gt;
        ///  &lt;g transform=&quot;translate(240,240) scale(240,-240)&quot;&gt;
        ///    &lt;polygon points=&quot;-0.54811715481171552,0.20920502092050208 0.7405857740585774,0.32217573221757323 0.55648535564853552,-0.606694560669456 &quot; stroke=&quot;black&quot; stroke-width=&quot;0.01&quot; fill=&quot;white&quot; /&gt;
        ///    &lt;polygon points=&quot;-0.61087866108786615,-0.32635983263598328 -0.68619246861924688,-0.7615062761506276 0.08368200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;480&quot; height=&quot;480&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;rect width=&quot;480&quot; height=&quot;480&quot; fill=&quot;rgb(1, 47, 135)&quot; /&gt;
        ///  &lt;defs&gt;
        ///    &lt;g id=&quot;map&quot;&gt;
        ///      &lt;polygon points=&quot;-0.0188087774294671,0.899581589958159 -0.689655172413793,-0.878661087866109 0.247648902821317,-0.866108786610879 &quot; stroke=&quot;black&quot; stroke-width=&quot;0.01&quot; fill=&quot;white&quot; /&gt;
        ///      &lt;polygon points=&quot;0.366771159874608,0.267782426778243 0.351097178683386,-0.121338912133891 0.821316614420063,-0.1589958 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;480&quot; height=&quot;480&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;rect width=&quot;480&quot; height=&quot;480&quot; fill=&quot;rgb(1, 47, 135)&quot; /&gt;
        ///  &lt;g transform=&quot;translate(240,240) scale(240,-240)&quot;&gt;
        ///    &lt;polygon points=&quot;0.14697853332425609,-0.00075762130579515308 -0.26289459311091157,0.57427694979271182 -0.553063553230448,0.24774216699500878 -0.54813901474277948,-0.20645180582917411 -0.30607900754123418,-0.68640490305039148 &quot; stroke=&quot;black&quot; stroke-width=&quot;0.01&quot; fill=&quot;white&quot; /&gt;
        ///  &lt;/g&gt;
        ///  &lt;circle cx=&quot;240 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
    }
}
