//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SRL.CommonsTests {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("SRL.CommonsTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;480&quot; height=&quot;480&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;rect width=&quot;480&quot; height=&quot;480&quot; fill=&quot;rgb(1, 47, 135)&quot; /&gt;
        ///  &lt;g transform=&quot;translate(240,240) scale(240,-240)&quot;&gt;
        ///    &lt;polygon points=&quot;-0.54811715481171552,0.20920502092050208 0.7405857740585774,0.32217573221757323 0.55648535564853552,-0.606694560669456 &quot; stroke=&quot;black&quot; stroke-width=&quot;0.01&quot; fill=&quot;white&quot; /&gt;
        ///    &lt;polygon points=&quot;-0.61087866108786615,-0.32635983263598328 -0.68619246861924688,-0.7615062761506276 0.08368200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://www.w3.org/2000/svg&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;svg&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;rect&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:attribute name=&quot;width&quot; type=&quot;xs:unsignedShort&quot; use=&quot;required&quot; /&gt;
        ///            &lt;xs:attribute name=&quot;height&quot; type=&quot;xs:unsignedShort&quot; use=&quot;required&quot; /&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapSchema {
            get {
                return ResourceManager.GetString("MapSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;order rotation=&quot;0.1&quot; destination=&quot;-0.41667,-0.2083&quot; /&gt;
        ///.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;order&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:attribute name=&quot;rotation&quot; type=&quot;xs:double&quot; use=&quot;required&quot; /&gt;
        ///      &lt;xs:attribute name=&quot;destination&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        internal static string OrderSchema {
            get {
                return ResourceManager.GetString("OrderSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;polygon points=&quot;-0.54811715481171552,0.20920502092050208 0.7405857740585774,0.32217573221757323 0.55648535564853552,-0.606694560669456 &quot; stroke=&quot;black&quot; stroke-width=&quot;0.01&quot; fill=&quot;white&quot; /&gt;
        ///.
        /// </summary>
        internal static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;polygon&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:attribute name=&quot;points&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        ///      &lt;xs:attribute name=&quot;stroke&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        ///      &lt;xs:attribute name=&quot;stroke-width&quot; type=&quot;xs:double&quot; use=&quot;required&quot; /&gt;
        ///      &lt;xs:attribute name=&quot;fill&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        ///    &lt;/xs:com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolygonSchema {
            get {
                return ResourceManager.GetString("PolygonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; width=&quot;480&quot; height=&quot;480&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;rect width=&quot;480&quot; height=&quot;480&quot; fill=&quot;rgb(1, 47, 135)&quot; /&gt;
        ///  &lt;defs&gt;
        ///    &lt;g id=&quot;map&quot;&gt;
        ///      &lt;polygon points=&quot;-0.0188087774294671,0.899581589958159 -0.689655172413793,-0.878661087866109 0.247648902821317,-0.866108786610879 &quot; stroke=&quot;black&quot; stroke-width=&quot;0.01&quot; fill=&quot;white&quot; /&gt;
        ///      &lt;polygon points=&quot;0.366771159874608,0.267782426778243 0.351097178683386,-0.121338912133891 0.821316614420063,-0.1589958 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://www.w3.org/2000/svg&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://www.w3.org/1999/xlink&quot; /&gt;
        ///  &lt;xs:element name=&quot;svg&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;rect&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:attribute name=&quot;width&quot; type=&quot;xs:unsignedShort&quot; use=&quot;req [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimulationSchema {
            get {
                return ResourceManager.GetString("SimulationSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:tns=&quot;http://www.w3.org/1999/xlink&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://www.w3.org/1999/xlink&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:attribute name=&quot;href&quot; type=&quot;xs:string&quot; /&gt;
        ///&lt;/xs:schema&gt;.
        /// </summary>
        internal static string SimulationSchemaXlink {
            get {
                return ResourceManager.GetString("SimulationSchemaXlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;svg width=&quot;480&quot; height=&quot;480&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///  &lt;rect width=&quot;480&quot; height=&quot;480&quot; fill=&quot;rgb(1, 47, 135)&quot; /&gt;
        ///  &lt;g transform=&quot;translate(240,240) scale(240,-240)&quot;&gt;
        ///    &lt;polygon points=&quot;0.14697853332425609,-0.00075762130579515308 -0.26289459311091157,0.57427694979271182 -0.553063553230448,0.24774216699500878 -0.54813901474277948,-0.20645180582917411 -0.30607900754123418,-0.68640490305039148 &quot; stroke=&quot;black&quot; stroke-width=&quot;0.01&quot; fill=&quot;white&quot; /&gt;
        ///  &lt;/g&gt;
        ///  &lt;circle cx=&quot;240 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://www.w3.org/2000/svg&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;svg&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;rect&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:attribute name=&quot;width&quot; type=&quot;xs:unsignedShort&quot; use=&quot;required&quot; /&gt;
        ///            &lt;xs:attribute name=&quot;height&quot; type=&quot;xs:unsignedShort&quot; use=&quot;required&quot; /&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VehicleSchema {
            get {
                return ResourceManager.GetString("VehicleSchema", resourceCulture);
            }
        }
    }
}
