//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.ModelsTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRL.ModelsTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;vmd xmlns=&quot;pl.pw.mini.KowMisPie.SRL&quot;&gt;
        ///  &lt;polygon&gt;
        ///    &lt;point x=&quot;1.1&quot; y=&quot;1.2&quot; /&gt;
        ///    &lt;point x=&quot;2.1&quot; y=&quot;2.2&quot; /&gt;
        ///    &lt;point x=&quot;3.1&quot; y=&quot;3.2&quot; /&gt;
        ///  &lt;/polygon&gt;
        ///  &lt;polygon&gt;
        ///    &lt;point x=&quot;1.3&quot; y=&quot;1.4&quot; /&gt;
        ///    &lt;point x=&quot;2.3&quot; y=&quot;2.4&quot; /&gt;
        ///    &lt;point x=&quot;3.3&quot; y=&quot;3.4&quot; /&gt;
        ///  &lt;/polygon&gt;
        ///&lt;/vmd&gt;.
        /// </summary>
        internal static string Map1 {
            get {
                return ResourceManager.GetString("Map1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;vvd xmlns=&quot;pl.pw.mini.KowMisPie.SRL&quot;&gt;
        ///  &lt;orientation&gt;
        ///    &lt;angle&gt;0&lt;/angle&gt;
        ///    &lt;point x=&quot;0.5&quot; y=&quot;0.5&quot; /&gt;
        ///  &lt;/orientation&gt;
        ///  &lt;polygon&gt;
        ///    &lt;point x=&quot;0&quot; y=&quot;0&quot; /&gt;
        ///    &lt;point x=&quot;2&quot; y=&quot;0&quot; /&gt;
        ///    &lt;point x=&quot;0&quot; y=&quot;2&quot; /&gt;
        ///  &lt;/polygon&gt;
        ///&lt;/vvd&gt;.
        /// </summary>
        internal static string Vehicle1 {
            get {
                return ResourceManager.GetString("Vehicle1", resourceCulture);
            }
        }
    }
}
